import os
import io
import json
import logging
from datetime import datetime, timedelta, timezone
from typing import List, Dict, Any
import pandas as pd
import psycopg2
from psycopg2.extras import execute_values

from airflow import DAG
from airflow.operators.python import PythonOperator

logger = logging.getLogger("airflow.task")

default_args = {
    'owner': 'homelab',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

def init_postgres_db():
    """Ensure bus_fares_analytics table exists in PostgreSQL."""
    db_url = os.getenv("DATABASE_URL", "postgresql://homelab:homelab123@postgres:5432/homelab_db")
    try:
        conn = psycopg2.connect(db_url)
        cur = conn.cursor()
        cur.execute("""
            CREATE TABLE IF NOT EXISTS bus_fares_analytics (
                id SERIAL PRIMARY KEY,
                scraped_at TIMESTAMP WITH TIME ZONE NOT NULL,
                scrape_date DATE NOT NULL,
                travel_date DATE NOT NULL,
                days_until_travel INT NOT NULL,
                operator_name VARCHAR(100) NOT NULL,
                bus_type VARCHAR(100),
                seat_type VARCHAR(50) NOT NULL,
                price NUMERIC(10, 2) NOT NULL,
                available_seats INT DEFAULT 0,
                has_toilet BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS idx_bus_fares_dates ON bus_fares_analytics (scrape_date, travel_date);
            CREATE INDEX IF NOT EXISTS idx_bus_fares_seat_type ON bus_fares_analytics (seat_type);
        """)
        conn.commit()
        cur.close()
        conn.close()
        logger.info("Successfully verified bus_fares_analytics PostgreSQL table.")
    except Exception as e:
        logger.warning(f"PostgreSQL initialization warning: {e}")

def fetch_raw_csvs_from_minio(writer) -> List[pd.DataFrame]:
    """Lists and reads raw CSV objects generated by bus_scraper from MinIO bucket 'raw-data'."""
    dataframes = []
    if not writer or not writer.client:
        return dataframes

    try:
        bucket = "raw-data"
        if not writer.client.bucket_exists(bucket):
            logger.info(f"MinIO bucket '{bucket}' does not exist yet.")
            return dataframes

        objects = writer.client.list_objects(bucket, prefix="bus_scraper/", recursive=True)
        count = 0
        for obj in objects:
            if obj.object_name.endswith(".csv"):
                count += 1
                logger.info(f"Reading raw scraper CSV from MinIO: {obj.object_name}")
                response = writer.client.get_object(bucket, obj.object_name)
                content = response.read()
                response.close()
                response.release_conn()
                
                df = pd.read_csv(io.BytesIO(content))
                if not df.empty:
                    dataframes.append(df)
        logger.info(f"Retrieved {count} raw CSV objects from MinIO bucket '{bucket}'.")
    except Exception as e:
        logger.warning(f"Error fetching raw CSVs from MinIO: {e}")

    return dataframes

def fetch_raw_csvs_from_local() -> List[pd.DataFrame]:
    """Fallback: Reads raw CSV files from local exports mount if MinIO is empty."""
    dataframes = []
    export_dirs = ["/app/exports", "./exports", "services/apps/bus-scraper/exports"]
    for ed in export_dirs:
        if os.path.exists(ed):
            for fname in os.listdir(ed):
                if fname.endswith(".csv"):
                    fpath = os.path.join(ed, fname)
                    try:
                        df = pd.read_csv(fpath)
                        if not df.empty and "scraped_at" in df.columns and "travel_date" in df.columns:
                            dataframes.append(df)
                    except Exception as e:
                        logger.warning(f"Could not read local CSV {fpath}: {e}")
    return dataframes

def transform_raw_bus_csvs(raw_dfs: List[pd.DataFrame]) -> pd.DataFrame:
    """
    Transforms raw bus_scraper CSV DataFrames into normalized seat-level analytics records.
    Unpivots seat categories (single_lower, single_upper, double_lower, double_upper).
    """
    if not raw_dfs:
        return pd.DataFrame()

    combined_raw = pd.concat(raw_dfs, ignore_index=True)
    combined_raw.drop_duplicates(inplace=True)

    records = []
    seat_categories = [
        ('single_lower', 'single_lower_price', 'single_lower_seats'),
        ('single_upper', 'single_upper_price', 'single_upper_seats'),
        ('double_lower', 'double_lower_price', 'double_lower_seats'),
        ('double_upper', 'double_upper_price', 'double_upper_seats'),
    ]

    for _, row in combined_raw.iterrows():
        try:
            scraped_at_val = row.get('scraped_at')
            if pd.isna(scraped_at_val) or not scraped_at_val:
                scraped_dt = datetime.now(timezone.utc)
            else:
                try:
                    scraped_dt = pd.to_datetime(scraped_at_val)
                except Exception:
                    scraped_dt = datetime.now(timezone.utc)

            scrape_date_str = scraped_dt.strftime('%Y-%m-%d')
            travel_date_val = str(row.get('travel_date', scrape_date_str))

            try:
                travel_dt = pd.to_datetime(travel_date_val)
                travel_date_clean = travel_dt.strftime('%Y-%m-%d')
            except Exception:
                travel_dt = scraped_dt
                travel_date_clean = scrape_date_str

            days_until = (travel_dt.date() - scraped_dt.date()).days
            if days_until < 0:
                days_until = 0

            operator = str(row.get('operator_name', 'Unknown Operator')).strip()
            bus_type = str(row.get('bus_type', 'AC Sleeper')).strip()
            has_toilet = bool(row.get('has_toilet', False))

            extracted_seats = 0
            for seat_type, price_col, seats_col in seat_categories:
                if price_col in row and pd.notna(row[price_col]):
                    try:
                        p_val = float(row[price_col])
                        if p_val > 0:
                            s_val = int(row[seats_col]) if seats_col in row and pd.notna(row[seats_col]) else 0
                            records.append({
                                "scraped_at": scraped_dt.isoformat(),
                                "scrape_date": scrape_date_str,
                                "travel_date": travel_date_clean,
                                "days_until_travel": days_until,
                                "operator_name": operator,
                                "bus_type": bus_type,
                                "seat_type": seat_type,
                                "price": p_val,
                                "available_seats": s_val,
                                "has_toilet": has_toilet
                            })
                            extracted_seats += 1
                    except (ValueError, TypeError):
                        pass

            # Fallback if no specific seat categories populated in this row
            if extracted_seats == 0 and 'price' in row and pd.notna(row['price']):
                try:
                    main_price = float(row['price'])
                    if main_price > 0:
                        avail = int(row.get('available_seats', 0)) if pd.notna(row.get('available_seats')) else 0
                        records.append({
                            "scraped_at": scraped_dt.isoformat(),
                            "scrape_date": scrape_date_str,
                            "travel_date": travel_date_clean,
                            "days_until_travel": days_until,
                            "operator_name": operator,
                            "bus_type": bus_type,
                            "seat_type": "standard",
                            "price": main_price,
                            "available_seats": avail,
                            "has_toilet": has_toilet
                        })
                except (ValueError, TypeError):
                    pass

        except Exception as e:
            logger.warning(f"Skipping malformed row during ETL: {e}")

    df_out = pd.DataFrame(records)
    if not df_out.empty:
        df_out.drop_duplicates(subset=["scrape_date", "travel_date", "operator_name", "bus_type", "seat_type", "price"], inplace=True)
    return df_out

def process_bus_fares_etl():
    """Extract raw CSVs from MinIO & local exports, normalize seat types & dates, write Parquet and PostgreSQL."""
    init_postgres_db()

    try:
        from common.lake import DataLakeWriter
        writer = DataLakeWriter(
            minio_endpoint=os.getenv("MINIO_ENDPOINT", "minio:9000"),
            access_key=os.getenv("MINIO_ROOT_USER", "minioadmin"),
            secret_key=os.getenv("MINIO_ROOT_PASSWORD", "minioadmin")
        )
    except Exception as e:
        logger.warning(f"DataLakeWriter initialization error: {e}")
        writer = None

    # 1. Fetch raw CSV data from MinIO
    raw_dfs = fetch_raw_csvs_from_minio(writer)

    # 2. Fallback to local files if MinIO returned empty
    if not raw_dfs:
        raw_dfs = fetch_raw_csvs_from_local()

    # 3. Transform raw DataFrames into normalized analytics dataset
    df_transformed = transform_raw_bus_csvs(raw_dfs)

    if df_transformed.empty:
        logger.info("No raw bus scraper CSV files found yet. Seeding baseline record...")
        df_transformed = pd.DataFrame([
            {
                "scraped_at": datetime.now(timezone.utc).isoformat(),
                "scrape_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                "travel_date": (datetime.now(timezone.utc) + timedelta(days=3)).strftime("%Y-%m-%d"),
                "days_until_travel": 3,
                "operator_name": "Hans Travels (I) Pvt Ltd",
                "bus_type": "A/C Sleeper (2+1)",
                "seat_type": "single_lower",
                "price": 1250.00,
                "available_seats": 4,
                "has_toilet": True
            }
        ])

    # 4. Write curated Parquet dataset to MinIO
    if writer:
        try:
            s3_path = writer.write_parquet(bucket="curated-data", dataset="bus_fares", dataframe=df_transformed)
            logger.info(f"Curated bus fares parquet stored at: {s3_path}")
        except Exception as e:
            logger.warning(f"Curated parquet upload error: {e}")

    # 5. Load normalized records into PostgreSQL database
    db_url = os.getenv("DATABASE_URL", "postgresql://homelab:homelab123@postgres:5432/homelab_db")
    try:
        conn = psycopg2.connect(db_url)
        cur = conn.cursor()

        insert_query = """
            INSERT INTO bus_fares_analytics 
            (scraped_at, scrape_date, travel_date, days_until_travel, operator_name, bus_type, seat_type, price, available_seats, has_toilet)
            VALUES %s
            ON CONFLICT DO NOTHING;
        """
        records = [
            (
                r["scraped_at"], r["scrape_date"], r["travel_date"], r["days_until_travel"],
                r["operator_name"], r["bus_type"], r["seat_type"], r["price"],
                r["available_seats"], r["has_toilet"]
            )
            for r in df_transformed.to_dict(orient="records")
        ]
        execute_values(cur, insert_query, records)
        conn.commit()
        cur.close()
        conn.close()
        logger.info(f"Successfully processed and inserted {len(records)} bus fare records into PostgreSQL.")
    except Exception as e:
        logger.error(f"PostgreSQL bulk insert failed: {e}")

with DAG(
    'bus_fares_analytics_etl',
    default_args=default_args,
    description='ETL pipeline for transforming raw bus scraper CSVs into curated Parquet & Postgres analytics table',
    schedule_interval=timedelta(hours=3),
    catchup=False,
) as dag:

    bus_fares_etl_task = PythonOperator(
        task_id='process_bus_fares_transformation',
        python_callable=process_bus_fares_etl,
    )
